apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: openshift-cluster-qm9cr-gpu-worker-g6e.2xlarge-us-east-2a
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: openshift-cluster-qm9cr
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: '1'
    machine.openshift.io/memoryMb: '32768'
    machine.openshift.io/vCPU: '8'
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: openshift-cluster-qm9cr
      machine.openshift.io/cluster-api-machineset: openshift-cluster-qm9cr-gpu-worker-g6e.2xlarge-us-east-2a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: openshift-cluster-qm9cr
        machine.openshift.io/cluster-api-machine-role: gpu-worker
        machine.openshift.io/cluster-api-machine-type: gpu-worker
        machine.openshift.io/cluster-api-machineset: openshift-cluster-qm9cr-gpu-worker-g6e.2xlarge-us-east-2a
        node-role.kubernetes.io/gpu-worker: ''
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu-worker: ''
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
      lifecycleHooks: {}
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          kind: AWSMachineProviderConfig
          ami:
            id: ami-0bc8dda494f111572
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 120
                volumeType: gp3
          capacityReservationId: ''
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: openshift-cluster-qm9cr-worker-profile
          instanceType: g6e.2xlarge
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - openshift-cluster-qm9cr-node
            - filters:
                - name: 'tag:Name'
                  values:
                    - openshift-cluster-qm9cr-lb
          subnet:
            id: subnet-011b74b6a28271a03
          tags:
            - name: kubernetes.io/cluster/openshift-cluster-qm9cr
              value: owned
          userDataSecret:
            name: worker-user-data
